name: 表述改进
description: 对模版说明或示例文档中的某些表述提出改进意见
body:
  - type: checkboxes
    attributes:
      label: 前提条件
      options:
        - label: 确定当前使用的是[最新的模版](https://github.com/MGG1996/DissertationUESTC/releases/latest)。
          required: true
        - label: 已浏览[待解决issue](https://github.com/MGG1996/DissertationUESTC/issues)和[已关闭issue](https://github.com/MGG1996/DissertationUESTC/issues?q=is%3Aissue%20state%3Aclosed)列表，且并未发现针对相同内容的调整建议。
          required: true
  - type: dropdown
    attributes:
      label: 待改进文本所属文件
      options:
        - readme.md
        - readme_en.md
        - tutorial.pdf
    validations:
      required: true
  - type: textarea
    attributes:
      label: 原表述内容
    validations:
      required: true
  - type: textarea
    attributes:
      label: 你建议的改进后的表述
    validations:
      required: true
